# Generated by Django 2.1.7 on 2019-03-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_auto_20190311_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='s_id',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to='Application.Student', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course_id', 'sec_id', 'semester', 'year')},
        ),
    ]
